import { StyleSheet } from "react-native";

export const textStyles = StyleSheet.create({
  h1Bold: {
    fontFamily: "Urbanist-Bold",
    fontWeight: "700",
    fontSize: 48,
    lineHeight: 48 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h1SemiBold: {
    fontFamily: "Urbanist-SemiBold",
    fontWeight: "600",
    fontSize: 48,
    lineHeight: 48 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h1Medium: {
    fontFamily: "Urbanist-Medium",
    fontWeight: "500",
    fontSize: 48,
    lineHeight: 48 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h1Regular: {
    fontFamily: "Urbanist-Regular",
    fontWeight: "400",
    fontSize: 48,
    lineHeight: 48 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h2Bold: {
    fontFamily: "Urbanist-Bold",
    fontSize: 40,
    lineHeight: 40 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h2SemiBold: {
    fontFamily: "Urbanist-SemiBold",
    fontWeight: "600",
    fontSize: 40,
    lineHeight: 40 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h2Medium: {
    fontFamily: "Urbanist-Medium",
    fontWeight: "500",
    fontSize: 40,
    lineHeight: 40 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h2Regular: {
    fontFamily: "Urbanist-Regular",
    fontWeight: "400",
    fontSize: 40,
    lineHeight: 40 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h3Bold: {
    fontFamily: "Urbanist-Bold",
    fontWeight: "700",
    fontSize: 32,
    lineHeight: 32 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h3SemiBold: {
    fontFamily: "Urbanist-SemiBold",
    fontWeight: "600",
    fontSize: 32,
    lineHeight: 32 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h3Medium: {
    fontFamily: "Urbanist-Medium",
    fontWeight: "500",
    fontSize: 32,
    lineHeight: 32 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h3Regular: {
    fontFamily: "Urbanist-Regular",
    fontWeight: "400",
    fontSize: 32,
    lineHeight: 32 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h4Bold: {
    fontFamily: "Urbanist-Bold",
    fontWeight: "700",
    fontSize: 24,
    lineHeight: 24 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h4SemiBold: {
    fontFamily: "Urbanist-SemiBold",
    fontWeight: "600",
    fontSize: 24,
    lineHeight: 24 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h4Medium: {
    fontFamily: "Urbanist-Medium",
    fontWeight: "500",
    fontSize: 24,
    lineHeight: 24 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h4Regular: {
    fontFamily: "Urbanist-Regular",
    fontWeight: "400",
    fontSize: 24,
    lineHeight: 24 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h5Bold: {
    fontFamily: "Urbanist-Bold",
    fontWeight: "700",
    fontSize: 20,
    lineHeight: 20 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h5SemiBold: {
    fontFamily: "Urbanist-SemiBold",
    fontWeight: "600",
    fontSize: 20,
    lineHeight: 20 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h5Medium: {
    fontFamily: "Urbanist-Medium",
    fontWeight: "500",
    fontSize: 20,
    lineHeight: 20 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h5Regular: {
    fontFamily: "Urbanist-Regular",
    fontWeight: "400",
    fontSize: 20,
    lineHeight: 20 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h6Bold: {
    fontFamily: "Urbanist-Bold",
    fontWeight: "700",
    fontSize: 18,
    lineHeight: 18 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h6SemiBold: {
    fontFamily: "Urbanist-SemiBold",
    fontWeight: "600",
    fontSize: 18,
    lineHeight: 18 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h6Medium: {
    fontFamily: "Urbanist-Medium",
    fontWeight: "500",
    fontSize: 18,
    lineHeight: 18 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  h6Regular: {
    fontFamily: "Urbanist-Regular",
    fontWeight: "400",
    fontSize: 18,
    lineHeight: 18 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0,
  },
  bodyXlargeBold: {
    fontFamily: "Urbanist-Bold",
    fontWeight: "700",
    fontSize: 18,
    lineHeight: 18 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyXlargeSemiBold: {
    fontFamily: "Urbanist-SemiBold",
    fontWeight: "600",
    fontSize: 18,
    lineHeight: 18 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyXlargeMedium: {
    fontFamily: "Urbanist-Medium",
    fontWeight: "500",
    fontSize: 18,
    lineHeight: 18 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyXlargeRegular: {
    fontFamily: "Urbanist-Regular",
    fontWeight: "400",
    fontSize: 18,
    lineHeight: 18 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyLargeBold: {
    fontFamily: "Urbanist-Bold",
    fontWeight: "700",
    fontSize: 16,
    lineHeight: 16 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyLargeSemiBold: {
    fontFamily: "Urbanist-SemiBold",
    fontWeight: "600",
    fontSize: 16,
    lineHeight: 16 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyLargeMedium: {
    fontFamily: "Urbanist-Medium",
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 16 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyLargeRegular: {
    fontFamily: "Urbanist-Regular",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 16 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyMediumBold: {
    fontFamily: "Urbanist-Bold",
    fontWeight: "700",
    fontSize: 14,
    lineHeight: 14 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyMediumSemiBold: {
    fontFamily: "Urbanist-SemiBold",
    fontWeight: "600",
    fontSize: 14,
    lineHeight: 14 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyMediumMedium: {
    fontFamily: "Urbanist-Medium",
    fontWeight: "500",
    fontSize: 14,
    lineHeight: 14 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyMediumRegular: {
    fontFamily: "Urbanist-Regular",
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 14 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodySmallBold: {
    fontFamily: "Urbanist-Bold",
    fontWeight: "700",
    fontSize: 12,
    lineHeight: 12 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodySmallSemiBold: {
    fontFamily: "Urbanist-SemiBold",
    fontWeight: "600",
    fontSize: 12,
    lineHeight: 12 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodySmallMedium: {
    fontFamily: "Urbanist-Medium",
    fontWeight: "500",
    fontSize: 12,
    lineHeight: 12 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodySmallRegular: {
    fontFamily: "Urbanist-Regular",
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 12 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyXsmallBold: {
    fontFamily: "Urbanist-Bold",
    fontWeight: "700",
    fontSize: 10,
    lineHeight: 10 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyXsmallSemiBold: {
    fontFamily: "Urbanist-SemiBold",
    fontWeight: "600",
    fontSize: 10,
    lineHeight: 10 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyXsmallMedium: {
    fontFamily: "Urbanist-Medium",
    fontWeight: "500",
    fontSize: 10,
    lineHeight: 10 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
  bodyXsmallRegular: {
    fontFamily: "Urbanist-Regular",
    fontWeight: "400",
    fontSize: 10,
    lineHeight: 10 * 1.6,
    textDecorationLine: "none",
    letterSpacing: 0.2,
  },
});
